"""empty message

Revision ID: c877c2bd4e0d
Revises: 
Create Date: 2017-05-29 11:16:01.114331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c877c2bd4e0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gateway',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname')
    )
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('authenticated', sa.Boolean(), nullable=False),
    sa.Column('anonymous', sa.Boolean(), nullable=False),
    sa.Column('pw_salt', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('gateway_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gateway_id'], ['gateway.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('r_id', sa.Integer(), nullable=True),
    sa.Column('gateway_id', sa.Integer(), nullable=True),
    sa.Column('json_rule', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['gateway_id'], ['gateway.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('r_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule')
    op.drop_table('device')
    op.drop_table('user')
    op.drop_table('gateway')
    # ### end Alembic commands ###
